Initial port of Chorus FX
bitfieldaudio/OTTO pull request #139
Opened 2019-11-30 06:32 UTC by jpjamipark

Running into some bugs with the encoder values disappearing immediately + not updating properly until notes are pressed. Unsure if this is b/c of the port. Just putting this initial PR up for feedback since I'm new.

2019-11-30 11:43 UTC, jmidt commented
I will take a closer look later, but I think you need to reset the envelopes in the actionhandlers in the screen. With a env.resetSoft()

2019-11-30 13:13 UTC, topisani requested changes

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/audio.cpp
> +    //Goes from minimal to around 20 ms nominal delay.
Please run `clang-format` on all files

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/audio.hpp
> +    float depth_ = 0.f;
should be private, and down by the other variables

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/chorus.hpp
> +    /// Publish the rotation variable, which is shared between the audio and screen
copy paste error in doc comment: `rotation`

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/chorus.hpp
> +    std::unique_ptr<Screen> screen_;
everything below audio can be private

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/screen.cpp
> +      float brightness = powf(cosh(abs(feedback_)*1.5)*0.4, 0.3 * float(i));
Prefer to move variables like `brightness` (and anything else that is computed solely based on the properties) out to member variables, and compute them in the action handlers.

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/screen.hpp
> +    std::array<ui::vg::Color, 10> colour_list = {ui::vg::Colors::Blue,
this array should be constexpr and declared in the .cpp file. `vg::Color` is `constexpr`-enabled on `develop` now, so this should be doable if you pull from that.

2019-11-30 13:13 UTC, topisani commented on src/engines/fx/chorus/screen.hpp
> +    float delay_ = 0.f;
all of these variables should be private and declared down by the other variables.

2019-11-30 13:15 UTC, topisani commented on src/engines/fx/chorus/chorus.hpp
> +} // namespace otto::engines::chorus
```suggestion
} // namespace otto::engines::chorus
#include "audio.hpp"
#include "screen.hpp"
```
To fix travis errors

2019-12-02 01:35 UTC, jpjamipark commented on src/engines/fx/chorus/screen.cpp
> +      float brightness = powf(cosh(abs(feedback_)*1.5)*0.4, 0.3 * float(i));
It looks like `brightness` &  `head_height` also rely on the i value based on the head - so should I create an array of size `num_heads` and store brightness/head_height for each head ?

2019-12-02 06:31 UTC, jmidt commented
Yes, that sounds fine for now!

man. 2. dec. 2019 02.35 skrev jpjamipark <notifications@github.com>:

> *@jpjamipark* commented on this pull request.
> ------------------------------
>
> In src/engines/fx/chorus/screen.cpp
> <https://github.com/OTTO-project/OTTO/pull/139#discussion_r352392602>:
>
> > +    ctx.fillText(fmt::format("{}", std::round(100 * delay_)), x_pad, y_pad + number_shift);
> +
> +
> +    //Heads
> +    constexpr float spacing_constant = 10;
> +    constexpr int num_heads = 10;
> +
> +    float spacing = spacing_constant * delay_ + 10;
> +    Point start = {120 - delay_ * 50, 165};
> +
> +    OTTO_ASSERT(phase_ != nullptr);
> +
> +    for (int i=num_heads; i>=1; i--) {
> +      float head_height = wave_height * gam::scl::sinP9(gam::scl::wrap(*phase_ - 0.2f*(float)i, 1.f, -1.f));
> +      //This brightness calculation is HORRIBLY over-engineered...
> +      float brightness = powf(cosh(abs(feedback_)*1.5)*0.4, 0.3 * float(i));
>
> It looks like brightness & head_height also rely on the i value based on
> the head - so should I create an array of size num_heads and store
> brightness/head_height for each head ?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/OTTO-project/OTTO/pull/139?email_source=notifications&email_token=AHY3NVQQCLZAONEUWPCOUBTQWRQ7XA5CNFSM4JTFHUB2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCNPNXYQ#discussion_r352392602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHY3NVQ6OTL6Q5KNCMJQS23QWRQ7XANCNFSM4JTFHUBQ>
> .
>

2019-12-02 09:47 UTC, topisani commented on src/engines/fx/chorus/screen.cpp
> +      float brightness = powf(cosh(abs(feedback_)*1.5)*0.4, 0.3 * float(i));
yep, thats a great idea!

2019-12-12 18:11 UTC, jmidt commented
Merging this. I will finish this now.

2019-12-12 18:11 UTC, merged